[project]
name = "to-project"
version = "0.1.0"
description = "Python embedding server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.6",
    "pydantic>=2.10.3",
    "sentence-transformers>=3.3.1",
    "uvicorn>=0.34.0",
]
